---
name: CI

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: steampipe-plugins/*/go.sum

      - name: Install Steampipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://steampipe.io/install/steampipe.sh)"
          steampipe --version
          steampipe plugin install github
          steampipe plugin install net
          make -C steampipe-plugins/github

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: make --assume-old=favicon.svg --assume-old="favicon-[layer].svg.py"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Timeout the this step as a work-around for https://github.com/nextstrain/status/issues/5
        timeout-minutes: 10

      - if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Timeout to prevent publish job from holding up updates
    # <https://github.com/nextstrain/status/issues/42>
    timeout-minutes: 1
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

defaults:
  run:
    # This is the same as GitHub Action's `bash` keyword as of 20 June 2023:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    #
    # Completely spelling it out here so that GitHub can't change it out from under us
    # and we don't have to refer to the docs to know the expected behavior.
    shell: bash --noprofile --norc -eo pipefail {0}
