---
name: publish

on:
  push:
    branches:
      # XXX FIXME
      - trs/wip
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Steampipe
        run: |
          sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/HEAD/install.sh)"
          steampipe --version
          steampipe plugin install github
          steampipe plugin install net

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - run: make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: build/

      # XXX FIXME
      - if: github.ref == 'refs/heads/trs/wip'
        id: deployment
        uses: actions/deploy-pages@v2

defaults:
  run:
    # This is the same as GitHub Action's `bash` keyword as of 20 June 2023:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    #
    # Completely spelling it out here so that GitHub can't change it out from under us
    # and we don't have to refer to the docs to know the expected behavior.
    shell: bash --noprofile --norc -eo pipefail {0}
